backend: positional
constrain_outputs: true
mutation: standard
n_evals_per_individual: 5
n_functions: 9
n_generations: 5000
n_individuals: 10
n_nodes: 50
n_parallel_runs: 10
nan_replacement: -100000.0
p_mut_functions: 0.1
p_mut_inputs: 0.1
p_mut_outputs: 0.3
problem:
  environment: halfcheetah
  episode_length: 1000
  incremental_steps: 1
  maximize: true
recursive: false
seed: 0
selection:
  elite_size: 1
  type: truncation
solver: cgp
survival: parents
levels_back: 5