backend: positional
constrain_outputs: true
mutation: standard
n_evals_per_individual: 5
n_individuals: 100
n_parallel_runs: 1
nan_replacement: -100000.0
distance: false
p_mut_functions: 0.1
recursive: false
selection:
  elite_size: 10
  tour_size: 3
  type: tournament
survival: truncation
unhealthy_termination: true
use_input_constants: true
saving_interval: 100
seed: [ 100,101,102,103,104,105,106,107,108,109 ]
store_fitness_details_list: [ healthy, ctrl, forward ]
nested0:
  - crossover: true
    n_extra_registers: 5
    n_rows: 15
    p_mut_lhs: 0.3
    p_mut_rhs: 0.1
    solver: lgp
  - n_nodes: 50
    p_mut_inputs: 0.1
    p_mut_outputs: 0.3
    solver: cgp
nested1:
  - problem:
      environment: inverted_pendulum
      episode_length: 1000
      incremental_steps: 1
      maximize: true
    n_generations: 10
  - problem:
      environment: inverted_double_pendulum
      episode_length: 1000
      incremental_steps: 1
      maximize: true
    n_generations: 1000
  - problem:
      environment: reacher
      episode_length: 1000
      incremental_steps: 1
      maximize: true
    n_generations: 1000
  - problem:
      environment: swimmer
      episode_length: 1000
      incremental_steps: 1
      maximize: true
    n_generations: 1000
  - problem:
      environment: hopper
      episode_length: 1000
      incremental_steps: 1
      maximize: true
    n_generations: 1500
  - problem:
      environment: walker2d
      episode_length: 1000
      incremental_steps: 1
      maximize: true
    n_generations: 1500
  - problem:
      environment: halfcheetah
      episode_length: 1000
      incremental_steps: 1
      maximize: true
    n_generations: 500
  - problem:
      environment: miniant
      episode_length: 1000
      incremental_steps: 1
      maximize: true
    n_generations: 2500