wandb_version: 1

backend:
  desc: null
  value: positional
constrain_outputs:
  desc: null
  value: true
mutation:
  desc: null
  value: standard
n_evals_per_individual:
  desc: null
  value: 5
n_extra_registers:
  desc: null
  value: 5
n_functions:
  desc: null
  value: 9
n_generations:
  desc: null
  value: 1000
n_individuals:
  desc: null
  value: 10
n_parallel_runs:
  desc: null
  value: 10
n_rows:
  desc: null
  value: 15
nan_replacement:
  desc: null
  value: -100000.0
p_mut_functions:
  desc: null
  value: 0.1
p_mut_lhs:
  desc: null
  value: 0.3
p_mut_rhs:
  desc: null
  value: 0.1
problem:
  desc: null
  value:
    environment: ant
    episode_length: 1000
    incremental_steps: 1
    maximize: true
recursive:
  desc: null
  value: false
seed:
  desc: null
  value: 0
selection:
  desc: null
  value:
    elite_size: 1
    type: truncation
solver:
  desc: null
  value: lgp
survival:
  desc: null
  value: parents
n_in:
  desc: null
  value: 11
n_out:
  desc: null
  value: 3
n_registers:
  desc: null
  value: 19
genome_size:
  desc: null
  value: 60
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686304208.679919
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.16
      5: 0.15.2
      8:
      - 5
