backend: positional
constrain_outputs: true
mutation: standard
n_evals_per_individual: 5
n_extra_registers: 5
n_generations: 1000
n_individuals: 100
n_parallel_runs: 1
n_rows: 15
nan_replacement: -100000.0
p_mut_functions: 0.1
p_mut_lhs: 0.3
p_mut_rhs: 0.1
problem:
  environment: halfcheetah
  episode_length: 1000
  incremental_steps: 1
  maximize: true
recursive: false
seed: 0
selection:
  elite_size: 20
  tour_size: 5
  type: tournament
solver: lgp
survival: truncation