backend:
  desc: null
  value: positional
constrain_outputs:
  desc: null
  value: true
mutation:
  desc: null
  value: standard
n_evals_per_individual:
  desc: null
  value: 5
n_generations:
  desc: null
  value: 1000
n_individuals:
  desc: null
  value: 10
n_nodes:
  desc: null
  value: 50
n_parallel_runs:
  desc: null
  value: 10
nan_replacement:
  desc: null
  value: -100000.0
p_mut_functions:
  desc: null
  value: 0.1
p_mut_inputs:
  desc: null
  value: 0.1
p_mut_outputs:
  desc: null
  value: 0.3
problem:
  desc: null
  value:
    environment: ant
    episode_length: 1000
    incremental_steps: 1
    maximize: true
recursive:
  desc: null
  value: false
seed:
  desc: null
  value: 0
selection:
  desc: null
  value:
    elite_size: 1
    type: truncation
solver:
  desc: null
  value: cgp
survival:
  desc: null
  value: parents
levels_back:
  value: 5
n_in:
  desc: null
  value: 11
n_out:
  desc: null
  value: 3
buffer_size:
  desc: null
  value: 61
genome_size:
  desc: null
  value: 153
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686675665.675913
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.16
      5: 0.15.2
      8:
      - 5
